[package]
name = "Rust-Workshop-Desktop-Application"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "1.8.0"
lazy_static = "1.4.0"
regex = "1.10.2"
evalexpr = "12.0.1"

[build-dependencies]
slint-build = "1.8.0"
